#!/usr/bin/env python3

import argparse
import csv

import matplotlib.pyplot as plt

parser = argparse.ArgumentParser(
    description="Compare alignment entropies of unique Panaroo groups"
)
parser.add_argument(
    "-e", "--entropies", required=True,
    help="alignment_entropy.csv generated by Panaroo"
)
parser.add_argument(
    "-u", "--unique", required=True,
    help="TSV file containing groups unique to Panaroo"
)
parser.add_argument(
    "-o", "--output", required=True,
    help="Output boxplot of alignment entropies"
)
args = parser.parse_args()

entropies = {}

with open(args.entropies, "r") as fi:
    reader = csv.reader(fi, delimiter=",")

    for row in reader:
        group = row[0].removesuffix(".aln")
        entropy = float(row[1])
        entropies[group] = entropy

groups_unique = set()
entropies_unique = []

with open(args.unique, "r") as fi:
    reader = csv.DictReader(fi, delimiter="\t")

    for row in reader:
        group = row["Gene"]
        if group in entropies:
            groups_unique.add(group)
            entropies_unique.append(entropies[group])

entropies_common = [e for g, e in entropies.items() if g not in groups_unique]
data = [entropies_common, entropies_unique]

plt.boxplot(data, labels=["Common", "Panaroo Only"])
plt.ylabel("Alignment Entropy")
plt.savefig(args.output)
