#!/usr/bin/env python3

import argparse
import csv
import os
from subprocess import PIPE, Popen

from Bio import SeqIO

parser = argparse.ArgumentParser(
    description="Align sequences of new panqc groups"
)
parser.add_argument(
    "-n", "--new-groups", required=True,
    help="NSC.ClusterInfo.tsv generated by panqc"
)
parser.add_argument(
    "-f", "--fasta-folder", required=True,
    help="folder containing the group alignment fasta files"
)
parser.add_argument(
    "-o", "--output-folder", required=True,
    help="folder containing the alignment results of the new groups"
)
args = parser.parse_args()

os.makedirs(args.output_folder, exist_ok=True)

groups = {}

with open(args.new_groups, "r") as fi:
    reader = csv.DictReader(fi, delimiter="\t")

    for row in reader:
        name = row["NS_ClusterID"]
        subgroups = row["NS_ClusterName"].split("---")

        if name in groups:
            if subgroups != groups[name]:
                print("Warning: conflicting group definitions!")

        groups[name] = subgroups

for name, subgroups in groups.items():
    records = []

    for subgroup in subgroups:
        fasta_file = f"{args.fasta_folder}/{subgroup}.aln.fas"

        if not os.path.isfile(fasta_file):
            fasta_file = f"{args.fasta_folder}/{subgroup}.fasta"

        records.extend(SeqIO.parse(fasta_file, "fasta"))

    fasta_in = "\n".join(rec.format("fasta").rstrip() for rec in records)
    outfile = f"{args.output_folder}/{name}.aln.fas"
    cline = f"mafft --auto - > {outfile}"

    proc = Popen(cline, shell=True, stdin=PIPE, stderr=PIPE, text=True)
    _, stderr = proc.communicate(fasta_in)

    if proc.returncode:
        raise RuntimeError(f"MAFFT failed:\n{stderr}")
