#!/usr/bin/env python3

import argparse
import csv

from Bio import SeqIO

parser = argparse.ArgumentParser(
    description="Compare Panaroo refound genes to original pseudogenes"
)
parser.add_argument(
    "-g", "--genbank", required=True,
    help="GenBank file containing original annotation"
)
parser.add_argument(
    "-p", "--panaroo", required=True,
    help="GFF file generated by panaroo-generate-gff"
)
parser.add_argument(
    "-o", "--output", required=True,
    help="Output file containing overlap"
)
args = parser.parse_args()

pseudogenes = {}

for record in SeqIO.parse(args.genbank, "genbank"):
    pseudogenes[record.id] = []

    for feat in record.features:
        if "pseudo" in feat.qualifiers or "pseudogene" in feat.qualifiers:
            pseudogenes[record.id].append(feat)

annotated = 0
novel = 0

same_start_stop = 0
in_frame = 0

novels = []

with open(args.panaroo, "r") as fi:
    reader = csv.reader(fi, delimiter="\t")

    for row in reader:
        if len(row) < 9:
            continue

        valkeys = row[8].split("=")
        key = valkeys[0]
        attrs = {}

        for valkey in valkeys[1:-1]:
            parts = valkey.split(";")
            val = ";".join(parts[:-1])
            attrs[key] = val
            key = parts[-1]

        attrs[key] = valkeys[-1]

        if "refound" in attrs["ID"]:
            chrom = row[0]
            start = int(row[3])
            end = int(row[4])
            strand = 1 if row[6] == "+" else -1

            for feat in pseudogenes[chrom]:
                loc = feat.location

                if loc.strand != strand:
                    continue
                if start <= loc.start <= end or start <= loc.end <= end:
                    start_diff = abs(loc.start - start)
                    end_diff = abs(loc.end - end)

                    if start_diff % 3 == 0:
                        annotated += 1

                        if start_diff == 0 or end_diff == 0:
                            same_start_stop += 1
                        else:
                            in_frame += 1

                    elif end_diff % 3 == 0:
                        annotated += 1

                        if start_diff == 0 or end_diff == 0:
                            same_start_stop += 1
                        else:
                            in_frame += 1
                    else:
                        novel += 1
                        novels.append(f"{chrom}:{start}-{end}:{strand}")

                    break

with open(args.output, "w") as fo:
    writer = csv.writer(fo, delimiter="\t")
    writer.writerow(["Pseudo: Total", annotated])
    writer.writerow(["Pseudo: Same Start/Stop", same_start_stop])
    writer.writerow(["Pseudo: In Frame", in_frame])
    writer.writerow(["Novel", novel])
